version: '3.8'

services:
  mongodb:
    image: mongo:6
    container_name: ketivee-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  redis:
    image: redis:7
    container_name: ketivee-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  backend:
    build: ./backend
    container_name: ketivee-backend
    ports:
      - "6329:6329"
    environment:
      - MONGODB_URI=mongodb://root:example@mongodb:27017/ketivee-search?authSource=admin
      - REDIS_URL=redis://redis:6379
    depends_on:
      - mongodb
      - redis

volumes:
  mongodb_data:
  redis_data: